// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Ljuske za rad s OS',
      link: { type: 'doc', id: 'bash/index' },
      items: ['bash/bash-1', 'bash/bash-2'],
    },
    /*{
      type: 'category',
      label: 'Sistemski pozivi',
      link: { type: 'doc', id: 'sistemski-pozivi/index' },
      items: ['sistemski-pozivi/sistemski-pozivi-1', 'sistemski-pozivi/sistemski-pozivi-2'],
    },
    {
      type: 'category',
      label: 'Procesi',
      link: { type: 'doc', id: 'procesi/index' },
      items: ['procesi/procesi-1', 'procesi/procesi-2'],
    },
    'dretve/index',
    {
      type: 'category',
      label: 'Međuprocesna komunikacija',
      link: { type: 'doc', id: 'meduprocesna-komunikacija/index' },
      items: [
        'meduprocesna-komunikacija/dijeljena-memorija',
        'meduprocesna-komunikacija/memorijsko-mapiranje',
        'meduprocesna-komunikacija/cjevovod',
        'meduprocesna-komunikacija/imenovani-cjevovod',
        'meduprocesna-komunikacija/komunikacija-porukama',
        'meduprocesna-komunikacija/signali',
        'meduprocesna-komunikacija/uticnice',
      ],
    },
    'upravljanje-memorijom/index',
    'racunalna-sigurnost/index',*/
  ],
};

export default sidebars;
